server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 127.0.0.1
      database: spitdb
  redis:
    host: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    # 跨域访问
    prefer-ip-address: true
