server:
  port: 9007

spring:
  application:
    name: tensquare‐search
  data:
    elasticsearch:
      cluster‐nodes: 127.0.0.1:9300
      cluster-name: docker-cluster

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    # 跨域访问
    prefer-ip-address: true
