server:
  port: 9009

spring:
  application:
    name: tensquare‐sms #指定服务名
  rabbitmq:
    host: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    # 跨域访问
    prefer-ip-address: true
