spring:
  application:
    name: ad-gateway

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  # 设置统一公共访问前缀
  prefix: /hellodev
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      # 不跳过前缀
      # 127.0.0.1:9000/hellodev/ad-sponsor/create/adPlan
      # true : 网关会转发/create/adPlan 到工程  会错误
      # false : 网关会转发/ad-sponsor/create/adPlan 没问题
      strip-prefix: false
